---
- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Upgrade apt
  apt:
    name: "*"
    state: latest

- name: Install basic packages
  apt:
    name:
     - htop
     - iotop
     - byobu
     - zsh
     - fzf
     - bat
     - git
     - fonts-font-awesome
     - python3-pip
     - codium
     - terminator
     - docker-ce
     - docker-ce-cli
     - containerd.io
     - apt-transport-https
     - ca-certificates
    state: present

- name: Symbolically link batcat -> bat
  file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    owner: root
    group: root
    state: link
