---
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}-utilities-install.yml"

- name: Set up ansible
  pip:
    name:
      - molecule-podman
      - ansible-lint
      - molecule

- name: Download pycharm-ce
  get_url:
    url: https://download.jetbrains.com/python/pycharm-community-2021.1.1.tar.gz
    dest: /tmp
    owner: root
    group: root
    mode: 0644

- name: Install pycharm
  unarchive:
    src: /tmp/pycharm-community-2021.1.1.tar.gz
    dest: /opt/
    creates: /opt/pycharm-community-2021.1.1/
    copy: false

- name: Include oh-my-zsh setup
  include_tasks: oh-my-zsh.yml

- name: Create diff-so-fancy directory
  become: true
  ansible.builtin.file:
    path: /src/diff-so-fancy
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    state: directory
    mode: "0755"
  with_items: "{{ users }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"

- name: Install diff-so-fancy
  ansible.builtin.git:
    repo: "https://github.com/so-fancy/diff-so-fancy.git"
    dest: /src/diff-so-fancy
    version: master
    single_branch: True
