---
- name: Import key for VScodium
  ansible.builtin.rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

- name: Add repo for VScodium
  yum_repository:
    name: gitlab.com_paulcarroty_vscodium_repo
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
    enabled: true
    description: "VScodium"

- name: Upgrade repos
  dnf:
    name: "*"
    state: latest

- name: Install basic packages
  ansible.builtin.dnf:
    name:
     - htop
     - iotop
     - byobu
     - zsh
     - fzf
     - bat
     - git
     - fontawesome-fonts
     - python3-pip
     - codium
     - terminator
     - buildah
    state: present


