---
- name: Add vscode key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Copy yum repo
  copy:
    src: vs-code.repo
    dest: /etc/yum.repos.d/vs-code.repo

- name: Upgrade repos
  dnf:
    name: "*"
    state: latest

- name: Install basic packages
  ansible.builtin.dnf:
    name:
     - htop
     - iotop
     - byobu
     - zsh
     - fzf
     - bat
     - git
     - fontawesome-fonts
     - python3-pip
     - terminator
     - buildah
     - code
    state: present


