---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Create users
      ansible.builtin.user:
        name: nsimpson
        shell: /bin/bash
        state: present

    - name: Install findutils
      ansible.builtin.dnf:
        name: findutils
        state: present
  tasks:
    - name: "Include utilities"
      include_role:
        name: "utilities"
