---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Create users
      ansible.builtin.user:
        name: nathans
        shell: /bin/bash
        state: present
      changed_when: false
    - name: Install findutils
      ansible.builtin.dnf:
        name: findutils
        state: present
      when: ansible_distribution == 'RedHat'
    - name: Install gpgagent
      ansible.builtin.apt:
        name: gpg-agent
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'
  tasks:
    - name: "Include utilities"
      include_role:
        name: "utilities"
